#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source /etc/profile

#export PATH=$PATH:$HOME/AndroidSDK:$HOME/AndroidSDK/tools:$HOME/AndroidSDK/platform-tools:$HOME/bin:/usr/share/java

function sha () {  
echo -n $1 | sha512sum | awk '{ print $1 }'  
}
function gvisudo() {
    EDITOR="gvim -f" sudoedit "$1"
}
alias whatsup="inxi -I -t cm"
alias prettycode="astyle --style=kr -H -p -k3"
#alias rm="rm -I"
alias dirsize="du -sh"
alias xstart="exec startx"
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
setopt interactivecomments
